### ISSUE TITLE
impnattypo not working with Tex Live 2016

### ISSUE THREAD

**Issue by cmosek** [raphink/impnattypo#6]
Hi, 

I'm compiling document with LuaLaTex Version 0.95.0 (TeX Live 2016/Debian) and package impnattypo is not working. 

I've tried my documents and also test from git tree. There is no error message, just using this package has no effect.

As suggested on Tex stackexchange package needs some updating: http://tex.stackexchange.com/questions/318810/problem-with-impnattypo-package

Could you do that or at least tell what needs to be updated? 

Greetings, 
Mikołaj Kowalski

**Comment by raphink** [comment]
Thanks for the report. I'd certainly welcome a PR to fix this!

**Comment by cmosek** [comment]
Could you at least tell what needs to be updated?

I have quite a lot experience with TeX but very little with Lua

**Comment by raphink** [comment]
I have no idea what needs to be updated bth. I'd have to read through the LuaTeX changes or ask on tex.SE like you did. There's some good LuaTeX experts there.

**Comment by michal-h21** [comment]
@LSinev sure this was a common issue. 'impnattypo` used fixed numbers for checking values of `node.id` attributes. Around version 1.0 LuaTeX changed numbers used for identifiing node ids, so the code that depends on them failed. It is necessary to use `node.id "node type` instead.

**Comment by raphink** [comment]
Should be fixed by #7

**Comment by LSinev** [comment]
@raphink Please upload updated impnattypo package to CTAN (https://www.ctan.org/pkg/impnattypo) for others to benefit from this compatibility fix.
